INSERT INTO "results" ("resultId","raceId","driverId","constructorId","number","grid","position","positionText","positionOrder","points","laps","time","milliseconds","fastestLap","rank","fastestLapTime","fastestLapSpeed","statusId") VALUES ('5',18,6,3,8,13,6,'6',6,3,57,'','','50',14,'01:29.6',212.974,11);
INSERT INTO "results" ("resultId","raceId","driverId","constructorId","number","grid","position","positionText","positionOrder","points","laps","time","milliseconds","fastestLap","rank","fastestLapTime","fastestLapSpeed","statusId") VALUES ('7',18,7,5,14,17,7,'7',7,2,55,'','','22',12,'01:29.5',213.224,5);
INSERT INTO "results" ("resultId","raceId","driverId","constructorId","number","grid","position","positionText","positionOrder","points","laps","time","milliseconds","fastestLap","rank","fastestLapTime","fastestLapSpeed","statusId") VALUES ('8',18,8,6,1,15,8,'8',8,1,53,'','','20',4,'01:27.9',217.18,5);
INSERT INTO "results" ("resultId","raceId","driverId","constructorId","number","grid","position","positionText","positionOrder","points","laps","time","milliseconds","fastestLap","rank","fastestLapTime","fastestLapSpeed","statusId") VALUES ('9',18,9,2,4,2,'','R',9,0,47,'','','15',9,'01:28.8',215.1,4);
INSERT INTO "results" ("resultId","raceId","driverId","constructorId","number","grid","position","positionText","positionOrder","points","laps","time","milliseconds","fastestLap","rank","fastestLapTime","fastestLapSpeed","statusId") VALUES ('10',18,10,7,12,18,'','R',10,0,43,'','','23',13,'01:29.6',213.166,3);
INSERT INTO "results" ("resultId","raceId","driverId","constructorId","number","grid","position","positionText","positionOrder","points","laps","time","milliseconds","fastestLap","rank","fastestLapTime","fastestLapSpeed","statusId") VALUES ('11',18,11,8,18,19,'','R',11,0,32,'','','24',15,'01:30.9',210.038,7);
INSERT INTO "results" ("resultId","raceId","driverId","constructorId","number","grid","position","positionText","positionOrder","points","laps","time","milliseconds","fastestLap","rank","fastestLapTime","fastestLapSpeed","statusId") VALUES ('12',18,12,4,6,20,'','R',12,0,30,'','','20',16,'01:31.4',208.907,8);
INSERT INTO "results" ("resultId","raceId","driverId","constructorId","number","grid","position","positionText","positionOrder","points","laps","time","milliseconds","fastestLap","rank","fastestLapTime","fastestLapSpeed","statusId") VALUES ('13',18,13,6,2,4,'','R',13,0,29,'','','23',6,'01:28.2',216.51,5);


INSERT INTO "drivers" ("driverId","driverRef","number","code","forename","surname","dob","nationality","url") VALUES (527,'sachs','','','Eddie','Sachs','28/05/1927','American','http://en.wikipedia.org/wiki/Eddie_Sachs');
INSERT INTO "drivers" ("driverId","driverRef","number","code","forename","surname","dob","nationality","url") VALUES (528,'freeland','','','Don','Freeland','25/03/1925','American','http://en.wikipedia.org/wiki/Don_Freeland');
INSERT INTO "drivers" ("driverId","driverRef","number","code","forename","surname","dob","nationality","url") VALUES (529,'bettenhausen','','','Tony','Bettenhausen','12/09/1916','American','http://en.wikipedia.org/wiki/Tony_Bettenhausen');
INSERT INTO "drivers" ("driverId","driverRef","number","code","forename","surname","dob","nationality","url") VALUES (530,'weiler','','','Wayne','Weiler','09/12/1934','American','http://en.wikipedia.org/wiki/Wayne_Weiler');
INSERT INTO "drivers" ("driverId","driverRef","number","code","forename","surname","dob","nationality","url") VALUES (531,'foyt','','','Anthony','Foyt','16/01/1935','American','http://en.wikipedia.org/wiki/A.J._Foyt');
INSERT INTO "drivers" ("driverId","driverRef","number","code","forename","surname","dob","nationality","url") VALUES (532,'russo','','','Eddie','Russo','19/11/1925','American','http://en.wikipedia.org/wiki/Eddie_Russo');

INSERT INTO "circuits" ("circuitId","circuitRef","name","location","country","lat","lng","alt","url") VALUES (18,'interlagos','AutÃ_dromo JosÃ© Carlos Pace','SÃ£o Paulo','Brazil',-23.7036,-46.6997,'','http://en.wikipedia.org/wiki/Aut%C3%B3dromo_Jos%C3%A9_Carlos_Pace');
INSERT INTO "circuits" ("circuitId","circuitRef","name","location","country","lat","lng","alt","url") VALUES (19,'indianapolis','Indianapolis Motor Speedway','Indianapolis','USA',39.795,-86.2347,'','http://en.wikipedia.org/wiki/Indianapolis_Motor_Speedway');
INSERT INTO "circuits" ("circuitId","circuitRef","name","location","country","lat","lng","alt","url") VALUES (20,'nurburgring','NÃ_rburgring','NÃ_rburg','Germany',50.3356,6.9475,'','http://en.wikipedia.org/wiki/N%C3%BCrburgring');
INSERT INTO "circuits" ("circuitId","circuitRef","name","location","country","lat","lng","alt","url") VALUES (21,'imola','Autodromo Enzo e Dino Ferrari','Imola','Italy',44.3439,11.7167,'','http://en.wikipedia.org/wiki/Autodromo_Enzo_e_Dino_Ferrari');
INSERT INTO "circuits" ("circuitId","circuitRef","name","location","country","lat","lng","alt","url") VALUES (22,'suzuka','Suzuka Circuit','Suzuka','Japan',34.8431,136.541,'','http://en.wikipedia.org/wiki/Suzuka_Circuit');
INSERT INTO "circuits" ("circuitId","circuitRef","name","location","country","lat","lng","alt","url") VALUES (23,'osterreichring','A1-Ring','Spielburg','Austria',47.2197,14.7647,'','http://en.wikipedia.org/wiki/A1-Ring');
INSERT INTO "circuits" ("circuitId","circuitRef","name","location","country","lat","lng","alt","url") VALUES (24,'yas_marina','Yas Marina Circuit','Abu Dhabi','UAE',24.4672,54.6031,'','http://en.wikipedia.org/wiki/Yas_Marina_Circuit');
INSERT INTO "circuits" ("circuitId","circuitRef","name","location","country","lat","lng","alt","url") VALUES (25,'galvez','AutÃ_dromo Juan y Oscar GÃ¡lvez','Buenos Aires','Argentina',-34.6943,-58.4593,'','http://en.wikipedia.org/wiki/Aut%C3%B3dromo_Oscar_Alfredo_G%C3%A1lvez');

INSERT INTO "races" ("raceId","year","round","circuitId","name","date","time","url") VALUES (1002,2018,14,14,'Italian Grand Prix','2018-09-02','12:00:00','http://en.wikipedia.org/wiki/2018_Italian_Grand_Prix');
INSERT INTO "races" ("raceId","year","round","circuitId","name","date","time","url") VALUES (1003,2018,15,15,'Singapore Grand Prix','2018-09-16','12:00:00','http://en.wikipedia.org/wiki/2018_Singapore_Grand_Prix');
INSERT INTO "races" ("raceId","year","round","circuitId","name","date","time","url") VALUES (1004,2018,16,71,'Russian Grand Prix','2018-09-30','12:00:00','http://en.wikipedia.org/wiki/2018_Russian_Grand_Prix');
INSERT INTO "races" ("raceId","year","round","circuitId","name","date","time","url") VALUES (1005,2018,17,22,'Japanese Grand Prix','2018-10-07','05:00:00','http://en.wikipedia.org/wiki/2018_Japanese_Grand_Prix');
INSERT INTO "races" ("raceId","year","round","circuitId","name","date","time","url") VALUES (1006,2018,18,69,'United States Grand Prix','2018-10-21','19:00:00','http://en.wikipedia.org/wiki/2018_United_States_Grand_Prix');
INSERT INTO "races" ("raceId","year","round","circuitId","name","date","time","url") VALUES (1007,2018,19,32,'Mexican Grand Prix','2018-10-28','19:00:00','http://en.wikipedia.org/wiki/2018_Mexican_Grand_Prix');
INSERT INTO "races" ("raceId","year","round","circuitId","name","date","time","url") VALUES (1008,2018,20,18,'Brazilian Grand Prix','2018-11-11','16:00:00','http://en.wikipedia.org/wiki/2018_Brazilian_Grand_Prix');
INSERT INTO "races" ("raceId","year","round","circuitId","name","date","time","url") VALUES (1009,2018,21,24,'Abu Dhabi Grand Prix','2018-11-25','13:00:00','http://en.wikipedia.org/wiki/2018_Abu_Dhabi_Grand_Prix');